/** Exact display translations for shipped module metadata. Unknown or edited prose stays unchanged. */
const MODULE_LABELS: Record<string, string> = {
  "System Prompt": "系統提示詞",
  "The constitutional layer — the five constitutional rules, the ONE output format, verification doctrine, security protocol, hard prohibitions. Highest authority; wins every conflict.": "LifeOS 的核心規則層：五項核心規則、統一輸出格式、驗證準則、安全協定與禁止事項。",
  "Every turn (appended system prompt)": "每輪對話（附加系統提示詞）",
  "CLAUDE.md": "背景載入索引",
  "The routing table — where everything lives. Pulls the always-on @-imports: architecture summary, TELOS, principal + DA identity, projects, operational rules.": "列出各項內容的位置，並匯入持續使用的架構摘要、意圖與方向、使用者與助理身分、專案及操作規則。",
  "Every turn (auto-loaded + @-imports)": "每輪對話（自動載入與匯入）",
  "Operational Rules": "操作規則",
  "Principal-specific operating rules — model selection, versioning, deploy doctrine, design variety, releases, autonomy boundaries. @-imported every turn.": "使用者專屬的操作規則，包含模型選擇、版本管理、部署、設計差異、發布與自主權界線；透過匯入機制提供背景。",
  "Every turn (@-import via CLAUDE.md)": "每輪對話（透過 CLAUDE.md 匯入）",
  "LoadContext hook": "載入背景",
  "SessionStart injection — builds the LifeOS dynamic context block (learning frames, active work, architecture pointers) the session opens with.": "在對話開始時注入 LifeOS 動態背景，包括學習框架、進行中的工作及架構參考。",
  "SessionStart (every new session)": "對話開始（每次新對話）",
  "LoadMemory hook": "載入記憶",
  "Every-prompt injection of the hot-layer memory files (PRINCIPAL_MEMORY, DA_MEMORY) so each turn sees current memory.": "在每次收到訊息時注入使用者與助理的常用記憶檔案，讓每一輪取得目前的記憶。",
  "Every prompt (UserPromptSubmit)": "每次提交訊息",
  "The Algorithm (doctrine)": "思考流程準則",
  "The thinking loop itself — euphoric surprise as the target, the ISA as hill + instrument, the 16 done-claims with their teeth (HOOK/CHECK/SELF), the event nudge table, spend doctrine. Read at the start of any substantial run.": "定義思考循環、超越預期的目標、理想狀態文件、十六項完成要求及其檢查方式、事件提醒與資源使用準則；在較完整的工作開始時讀取。",
  "On any substantial run (first action)": "較完整的工作開始時（第一個動作）",
  "Algorithm Changelog": "思考流程變更紀錄",
  "Every doctrine version's full history: what changed, why, migration and rollback recipes. Doctrine files stay lean; history lives here.": "保存各版準則的完整歷史：修改內容、原因、遷移與還原方式，讓準則本身保持精簡。",
  "On demand": "按需載入",
  "ISA Format Spec": "理想狀態文件格式",
  "The contract for the Ideal State Artifact — section order, claim shapes, ID stability, the Splitting and Variation tests. The ISA is where 'done' gets written down before building.": "規範理想狀態文件的章節順序、要求寫法、識別碼穩定性，以及拆分與變化檢查，讓完成條件在實作前寫清楚。",
  "During a run (ISA work)": "工作進行中（處理理想狀態文件時）",
  "ISA System doc": "理想狀態系統說明",
  "How the ISA subsystem works end to end — lifecycle, homes (repo ISA vs MEMORY/WORK), sync to Pulse, resume semantics.": "說明理想狀態文件的完整運作方式：生命週期、儲存位置、同步至工作台，以及恢復工作的方式。",
  "On demand (ISA architecture)": "按需載入（理想狀態系統架構）",
  "ISA skill": "理想狀態文件技能",
  "The skill that scaffolds, interviews, scores completeness, reconciles, and appends to ISAs — the operational front door to the ISA system.": "建立文件骨架、訪談、評估完整度、整合與補充理想狀態文件，是此系統的操作入口。",
  "On invocation (ISA operations)": "呼叫技能時（理想狀態文件操作）",
  "ISASync hook": "同步理想狀態",
  "Mirrors every ISA write to the work registry (work.json) → Pulse. This write IS the run telemetry — claim 13's carrier.": "將每次理想狀態文件寫入同步至工作登錄與工作台，形成執行過程的紀錄。",
  "Event-driven (ISA writes)": "事件觸發（寫入理想狀態文件）",
  "CheckpointPerISC hook": "完成條件檢查點",
  "Auto git-commit on every claim close (`[ ]`→`[x]`) — evidence trail per closed claim, part of claim 8's teeth.": "每關閉一項完成要求便自動建立 Git 提交，保留逐項驗證與完成的證據。",
  "Event-driven (ISA claim edits)": "事件觸發（修改完成條件）",
  "ISARenderOnStop hook": "更新理想狀態預覽",
  "Re-renders edited ISAs at end-of-turn so the HTML mirror stays current with the artifact.": "在一輪工作結束時重新呈現已修改的理想狀態文件，讓 HTML 預覽與文件保持一致。",
  "Stop (turn end, when ISAs changed)": "回應結束（理想狀態文件有變更時）",
  "AlgorithmNudge hook": "流程即時提醒",
  "The live event layer — deterministic nudges fired at the moment they're answerable: skill-routing, late-ISA, depth directives (always-on); probe-failure, mid-run messages, spend checks (run-scoped).": "在適合回應的時點觸發固定規則提醒，涵蓋技能選擇、理想狀態文件、深度要求、探測失敗、中途訊息及資源檢查。",
  "Event-driven (every prompt / tool result)": "事件觸發（每次訊息或工具結果）",
  "VerificationGate hook": "驗證檢查",
  "Mechanical teeth for claim 8 — no claim closes without tool evidence of the right modality; web/UI claims need a real browser, appearance claims need viewed pixels.": "要求完成條件具備相符的工具證據；網頁與介面要求需實際瀏覽器驗證，外觀要求需檢視畫面。",
  "Event-driven (claim close / stop)": "事件觸發（完成條件關閉或回應結束）",
  "StopGates hook": "回應結束檢查",
  "The ONE Stop-event gate runner — merges the per-turn gate spawns into a single process reading stdin once; each gate file stays owner of its logic.": "將每輪結束時的各項檢查整合成一次執行，各檢查檔案仍保留自己的判定邏輯。",
  "Stop (every turn end)": "每輪回應結束",
  "FormatGate hook": "輸出格式檢查",
  "Deterministic Stop-hook teeth for the ONE output format — banner first, closer last, hook-fed memory lines echoed verbatim.": "在回應結束時檢查統一輸出格式，包括開頭、結尾與事件處理提供的記憶內容。",
  "SpendAuditor hook": "資源使用檢查",
  "Outcome-side spend verification (claim 15) — catches the heavy ask answered inline with zero capability use and no stated reason.": "從成果檢查資源使用，辨識複雜要求是否在未使用相關能力且未說明原因的情況下直接作答。",
  "Event-driven (turn analysis)": "事件觸發（分析本輪工作）",
  "WritingGate hook": "發布文字檢查",
  "Publication gate — prose authored for the principal that will be published must pass the _WRITING audit + a real Pangram run, SHA-verified; typing the audit line without running the tool does not pass.": "檢查準備發布的文字是否完成寫作稽核及 Pangram 檢測，並以內容雜湊核對；只有寫出稽核聲明並不算通過。",
  "Stop (publication signals)": "回應結束（偵測到發布需求）",
  "DriftReminder hook": "語氣與格式提醒",
  "Voice/format drift nudge — flags when output slides away from the DA voice contract so the next turn corrects.": "辨識輸出是否偏離助理的語氣約定，提醒下一輪修正。",
  "Philosophy": "設計理念",
  "Why the system works this way — Deutsch epistemology, hard-to-vary claims, ideal-state prompting, the bitter-lesson stance on scaffolding.": "說明系統設計的認識論、難以任意改動的解釋、理想狀態提示，以及對額外流程規則的取捨。",
  "On demand (explaining / documenting)": "按需載入（說明或撰寫文件）",
  "Verification Doctrine": "驗證準則詳解",
  "The ONE home of the six incident-derived verification rules (modality fidelity, defer-never-substitute, appearance ≠ existence, reproduce-before-fixing, temporal fidelity, restore-parity). Cites incidents by INC-ID.": "彙整由事件經驗形成的六項驗證規則：證據形式相符、延期而不替代、外觀與存在有別、修正前重現、時間相符，以及恢復一致性。",
  "On demand (web/UI verification)": "按需載入（網頁或介面驗證）",
  "Incidents": "問題事件紀錄",
  "The self-improvement loop's evidence base — one INC-YYYYMMDD-<slug>.md per verified LifeOS failure, cited by ID from rules and doctrine; narratives live here and only here.": "保存已確認的 LifeOS 失敗事件，作為系統改進的證據；規則與準則以事件識別碼引用詳細紀錄。",
  "On demand (following an INC citation)": "按需載入（追查事件引用）",
  "Self-Healing": "系統自我修復",
  "Where a new rule or fix structurally lives — hooks for enforcement, CLAUDE.md for routing, skills for domain behavior, KNOWLEDGE for facts. Fix the system, not your notes.": "說明新規則與修正應放在哪裡：事件處理負責約束、索引負責指引、技能負責領域行為、知識庫保存事實。",
  "On demand (encoding a learning / degraded state)": "按需載入（保存經驗或處理運作異常）",
  "Operational Rules Expanded": "操作規則詳解",
  "The mechanics behind every operational rule — full rationale, incident history, procedures, same section names as the operative core. Read when a rule fires and you need the how.": "保存各項操作規則的完整理由、事件歷史與執行程序；需要了解實際做法時讀取。",
  "On demand (a rule fires)": "按需載入（規則觸發）",
  "Writing Style Backstop": "寫作風格參考",
  "The complete voice doctrine — ban lists, banned rhythms, the pre-emit checks, long-form exemplars. Loaded when auditing writing or a drift flag fires.": "完整的語氣與寫作規範，包含避免使用的詞句與節奏、輸出前檢查，以及長篇範例。",
  "On demand (writing audit / drift flag)": "按需載入（寫作檢查或語氣偏離）",
  "Summarize hotkey": "摘要快捷鍵",
  "browser hotkey on any page": "在任何網頁使用瀏覽器快捷鍵",
  "summarize worker": "摘要工作單元",
  "Bookmarks → idea-issues": "書籤轉為想法議題",
  "bookmark sweep": "掃描書籤",
  "social-bookmark skill → Type:queue": "社群書籤技能 → 工作佇列",
  "Bookmarks → summarize (cloud)": "雲端書籤摘要",
  "every-minute cron": "每分鐘排程",
  "bookmark-summarize worker → sheet": "書籤摘要工作單元 → 試算表",
  "Harvest → Knowledge": "收集內容至知識庫",
  "harvest on a URL/video/text": "收集網址、影片或文字",
  "harvest skill → classify worker": "內容收集技能 → 分類工作單元",
  "Voice markers": "語音標記",
  "“begin idea … end idea” on the wearable": "在穿戴裝置說出「begin idea … end idea」",
  "lifelog skill": "生活紀錄技能",
  "Feed pipeline": "資訊流管線",
  "RSS/YouTube/social polling": "輪詢 RSS、YouTube 與社群內容",
  "feed-api → poller → processor": "資訊流介面 → 輪詢器 → 處理器",
  "Reader save": "閱讀器儲存",
  "save/summarize in the reader": "在閱讀器儲存或產生摘要",
  "summarize worker → ledger (service binding)": "摘要工作單元 → 紀錄（服務綁定）",
  "CLI / skill capture": "指令或技能擷取",
  "amber capture <url|text>": "執行 amber capture <url|text>",
  "amber CLI → ledger": "琥珀紀錄 CLI → 紀錄",
  "Reader upvote → capture": "閱讀器按讚後擷取",
  "thumbs-up on a reader item": "為閱讀器項目按讚",
  "—": "—",
  "Gesture / wearable trigger": "手勢或穿戴裝置觸發",
  "physical trigger from anywhere": "從任何地方以實體操作觸發",
  "Email → capture": "電子郵件擷取",
  "forward to a capture address": "轉寄至擷取信箱",
  "Bookmark cron → sheet": "書籤排程 → 試算表",
  "Surface saves → sheet": "閱讀器儲存 → 試算表",
  "Hotkey → sheet": "快捷鍵 → 試算表",
  "SEEN_BOOKMARKS KV keys — written only after a successful summarize → sheet send; 90-day KV TTL, so this is a rolling window": "只計入成功完成摘要並送至試算表後寫入的 SEEN_BOOKMARKS 鍵；資料保留 90 日，因此數字呈現滾動期間。",
  "ledger rows with source=surface (dual-written to sheet + ledger since 2026-07-08)": "來源為 surface 的紀錄筆數；自 2026-07-08 起，同時寫入試算表與紀錄。",
  "not yet instrumented — no local counter until the hotkey path is wired to the ledger (Phase 3)": "尚未建立追蹤；快捷鍵路徑在第三階段接入紀錄之前，沒有本機計數器。",
  "No hourly read yet — the insight job runs on the hour.": "尚無每小時洞察；洞察工作在整點執行。",
  "Insight file unreadable.": "無法讀取洞察檔案。",
  "Claude Code (derived from session cadence)": "Claude Code（依對話間隔推算）",
  "App focus": "應用程式焦點",
  "Which macOS app is frontmost, sampled every poll": "每次輪詢記錄目前位於最前方的 macOS 應用程式",
  "Git commits": "Git 提交",
  "New commits across your configured repos": "已設定儲存庫中的新增提交",
  "LifeOS sessions": "LifeOS 對話",
  "Algorithm & session activity from the work-events log": "工作事件紀錄中的思考流程與對話活動",
  "GitHub activity": "GitHub 活動",
  "Your commits & pull requests on GitHub — including remote/API work": "GitHub 上的提交與拉取請求，包含遠端及 API 工作"
};

const SKILL_NAMES: Record<string, string> = {
  "ApertureOscillation": "視角切換",
  "Aphorisms": "格言收藏",
  "Apify": "平台資料擷取",
  "ArXiv": "學術論文搜尋",
  "Art": "視覺創作",
  "AudioEditor": "音訊剪輯",
  "BeCreative": "創意探索",
  "BiasCheck": "偏誤檢查",
  "BitterPillEngineering": "提示規則精簡",
  "BrightData": "網頁資料擷取",
  "CMUX": "多代理工作台",
  "Cortex": "記憶資料庫",
  "Council": "多方討論",
  "CreateCLI": "建立命令列工具",
  "CreateSkill": "建立技能",
  "Daemon": "公開近況",
  "DetectAI": "文字風格檢查",
  "Evals": "代理評測",
  "ExtractWisdom": "智慧提煉",
  "Fabric": "提示範本庫",
  "FirstPrinciples": "第一性原理",
  "HTML": "網頁成果呈現",
  "Hardening": "測試強化",
  "ISA": "理想狀態文件",
  "Ideate": "構想演化",
  "Interceptor": "瀏覽器操作",
  "Interview": "目標訪談",
  "IterativeDepth": "多角度深入分析",
  "LifeOS": "生活作業系統",
  "LocalIntelligence": "在地資訊",
  "Loop": "持續改進",
  "Migrate": "資料匯入",
  "Novelty": "新解釋探索",
  "Optimize": "目標優化",
  "PrivateInvestigator": "公開背景研究",
  "Prompting": "提示詞設計",
  "RedTeam": "反方檢驗",
  "Remotion": "程式化影片",
  "Research": "資料研究",
  "RootCauseAnalysis": "根本原因分析",
  "Sales": "提案與銷售",
  "Science": "科學方法",
  "SecurityMarketData": "資安市場情報",
  "SuggestSkills": "技能建議",
  "SystemsThinking": "系統思考",
  "Teach": "互動教學",
  "Telos": "意圖與方向",
  "ThreatModel": "威脅建模",
  "Tldraw": "圖解畫布",
  "Trim": "背景內容精簡",
  "USMetrics": "美國指標",
  "Upgrade": "系統改進",
  "Vitals": "電腦運作狀態",
  "Webdesign": "網頁設計",
  "WorldThreatModel": "長期情境分析",
  "WriteStory": "故事創作"
};

/** Matches only the unmodified metadata bundled with LifeOS; never translates skill document bodies. */
const SKILL_DESCRIPTIONS: Record<string, string> = {
  "3-pass scope oscillation that holds a question constant while shifting zoom — narrow/tactical, wide/strategic, then synthesis — to surface design tensions, scope recommendations, and coherence assessments invisible at any single zoom level. USE WHEN aperture oscillation, oscillate scope, zoom in and out, tactical vs strategic, scope framing, design tension, system coherence check, local vs global design, wrong scope, scope negotiation. NOT FOR lens rotation across angles (use IterativeDepth).": "從局部、整體到整合，透過三輪觀察釐清設計取捨。",
  "Curated aphorism collection with CRUD — content-based matching, themed search, thinker research, DB maintenance. Quotes organized by author/theme/context/usage to prevent repetition. Four workflows: FindAphorism, AddAphorism, ResearchThinker, SearchAphorisms. Themes: Stoicism, Wisdom, Truth-seeking, Excellence, Resilience, Curiosity. USE WHEN aphorism, quote, find a quote, research thinker, add aphorism, quote for newsletter, what did X say about, quote bank. NOT FOR creative writing or social posts.": "整理、搜尋與研究格言，依作者、主題及用途維護收藏。",
  "Scrapes social platforms, business data, and e-commerce via Apify actors — Instagram, LinkedIn, TikTok, YouTube, Facebook, Google Maps, Amazon, and web crawls — filtering in code. USE WHEN scrape Instagram, scrape LinkedIn, scrape TikTok, scrape YouTube, scrape Facebook, Google Maps leads, Amazon reviews, business intelligence, multi-platform social listening, competitive analysis, lead generation, social monitoring, Apify actors, web crawl, extract contacts. NOT FOR X/Twitter account operations like posting, threads, or bookmarks (those need a dedicated X API client), 4-tier progressive scraping with proxy escalation (use BrightData), or real-Chrome bot bypass and computer use (use Interceptor).": "透過 Apify 擷取社群、商業與電商資料。",
  "Search and retrieve arXiv academic papers by topic, category, or paper ID — with AlphaXiv-enriched AI-generated overviews. Uses arXiv Atom API across cs.AI/cs.LG/cs.CL/cs.CR/cs.MA/cs.SE/cs.IR. Three workflows: Latest, Search, Paper. USE WHEN arxiv, papers, latest papers, research papers, recent ML papers, paper lookup, summarize paper, latest LLM papers, AI safety papers, cs.AI latest. NOT FOR general research (Research), URL parsing, or annual reports.": "依主題、分類或論文識別碼搜尋及讀取 arXiv 論文。",
  "Static visual content across 20+ formats — diagrams, mermaid, infographics, D3 dashboards, comics, icons, wallpaper — via Nano Banana Pro (default), Nano Banana, and Flux. USE WHEN art, illustration, diagram, flowchart, infographic, header image, blog social thumbnail, visualize, generate image, mermaid, architecture diagram, comic, icon, blog art, framework diagram, D3 chart, remove background, wallpaper. NOT FOR locked house-style YouTube/channel/video thumbnails, video or animation (use Remotion), or web UI design and integrated frontend layout (use Webdesign).": "製作圖解、資訊圖、插畫、圖示與其他靜態視覺作品。",
  "AI audio editing pipeline: Whisper word-level transcription → Claude segment classification (KEEP/CUT_FILLER/CUT_FALSE_START/CUT_STUTTER/CUT_DEAD_AIR) → ffmpeg with 40ms qsin crossfades and room-tone fill → optional Cleanvoice cloud polish; plus GateScan/GateRepair for noise-gate ticking artifacts. Modes: --preview, --aggressive, --polish. Workflow: Clean. USE WHEN clean audio, edit audio, remove filler words, clean podcast, remove ums, cut dead air, polish audio, trim recording, cut stutters, ticking audio, clicking audio, audio clicks, gate artifacts, popping audio. NOT FOR video composition (use Remotion).": "結合語音轉錄與語意判斷，整理停頓與冗詞並剪輯音訊。",
  "Divergent ideation and corpus expansion via Verbalized Sampling plus extended thinking — single-shot generates several internally diverse candidates and surfaces the strongest, or expands a seed corpus into a diverse dataset for evals and test sets. USE WHEN be creative, brainstorm, divergent ideas, creative solutions, maximum creativity, tree of thoughts, radically different, name this, creative angle, expand this corpus, synthetic data, generate diverse examples, create test set. NOT FOR multi-cycle evolutionary ideation with Lamarckian meta-learning (use Ideate).": "產生多種差異明顯的構想，拓展思考方向。",
  "Three-layer bias analysis on any URL, file, or text — auto-fetches the content and any cited study, then audits data-level biases, source conflicts of interest, and journalism-added distortions, separating what the data supports from what's editorialized. USE WHEN bias analysis, analyze bias, bias check, check this study, who funded this, is this source biased, fact-check article, methodological flaws, source credibility, what's wrong with this claim. NOT FOR psychological author analysis, research synthesis (use Research), entity due diligence.": "檢查資料偏誤、來源利益衝突，以及報導加入的扭曲。",
  "Audits any AI instruction set for over-prompting using the core test — would a smarter model make this rule unnecessary? Applies Five Questions to every rule (Claude already does this? Contradiction? Redundant? One-off fix? Vague?) then classifies as CUT/RESOLVE/MERGE/EVALUATE/SHARPEN/MOVE/KEEP. Workflows: Audit (full system, token savings), QuickCheck (single file). Principle: less scaffolding = better output. USE WHEN BPE, bitter pill, audit setup, over-prompting, trim instructions, dead weight, simplify setup, clean up CLAUDE.md. NOT FOR attacking logical flaws in ideas (use RedTeam).": "檢查指令集是否過度設計，找出可刪減的流程與規則。",
  "4-tier progressive web scraping that auto-escalates WebFetch to curl to Interceptor to Bright Data proxy for bot detection and CAPTCHAs, with single-URL and multi-page crawl modes, output as markdown. USE WHEN Bright Data, scrape URL, web scraping, bot detection, crawl site, CAPTCHA, can't access, site blocking, extract page content, scrape whole site, spider domain, convert URL to markdown, getting blocked. NOT FOR simple public content (use WebFetch directly), social platform scraping with named actors (use Apify), or real-Chrome bot bypass with logged-in sessions and zero CDP fingerprint (use Interceptor).": "依網站限制逐步選擇適合的擷取方式，整理網頁內容。",
  "Drives cmux as an agent cockpit to boot, race, and monitor visible agent teams. Mac-only. USE WHEN cmux, agent cockpit, boot an agent team, orchestrate agents, three-tier orchestration, agent race, needle-in-haystack hotfix, agent fleet, 2x2 fleet, watch/monitor my agents, scale compute to scale impact, send a prompt to a running agent, multiplexer, terminal cockpit, orchestrator lead worker. NOT FOR one-shot in-harness subagents with no terminal to watch (use Agent/Workflow), the Pulse dashboard itself (cmux feeds it, use Pulse), browser deploy-verification (use Interceptor), or Linux/Windows (cmux is Mac-only — use tmux).": "使用 cmux 啟動、觀察與協調可見的代理工作團隊。",
  "Operate Cortex, the LifeOS memory system — the typed Knowledge Archive (People, Companies, Ideas, Research with typed related: links) plus recall of prior work sessions, ISAs, and conversations. Search, add, harvest, develop, ingest, distill, graph-navigate, recall. USE WHEN cortex, knowledge, knowledge base, search knowledge, what do we know about, archive, harvest, knowledge status, develop note, add to knowledge, ingest, contradictions, knowledge graph, retrieve, mine conversations, distill, weekly digest, cortex digest, context search, prior work, recall, remember, previous sessions, context recovery, what did we do, find session, search history, resume, pick up where we left off, cold start, yesterday's work, last week, the one about. NOT FOR published-content semantic search across blog/newsletter/X/LinkedIn, or one-shot URL/YouTube ingestion via the Arbol harvester pipeline.": "搜尋與管理人物、組織、想法、研究及過往工作記憶。",
  "Multi-agent collaborative debate producing visible round-by-round transcripts with real intellectual friction — members are topic-briefed custom agents, run as a 3-round DEBATE or a 1-round QUICK check, to find the best path. USE WHEN council, debate, multiple perspectives, weigh options, deliberate, get different views, what would experts say, pros and cons. NOT FOR pure adversarial attack (use RedTeam).": "讓多個代理從不同角度辯論，保留可追溯的討論過程。",
  "Generates production-ready TypeScript CLIs via a 3-tier template system (manual arg parsing, Commander.js, oclif), each shipping full implementation, docs, package.json, strict config, JSON output, and exit-code compliance. USE WHEN create CLI, build CLI, command-line tool, wrap API, add command, upgrade tier, TypeScript CLI. NOT FOR LifeOS skill scaffolding (use CreateSkill).": "建立具型別、文件與驗證能力的 TypeScript 命令列工具。",
  "Mandatory orchestrator for all LifeOS skill work — creating, editing, adding a workflow or tool, renaming, validating, or canonicalizing any skill. Handrolling skill files is forbidden; owns the full lifecycle: scaffold, validate, canonicalize, test, improve. USE WHEN create skill, new skill, make a skill, build a skill, set up a skill, private skill, make a X skill, add a workflow, add a tool, edit/change/update/rename a skill, skill frontmatter, validate skill, check skill, canonicalize, scaffold skill, test skill, improve skill, optimize description, skill not triggering, overtriggering. NOT FOR TypeScript CLI generation (use CreateCLI).": "建立、編輯、驗證及整理 LifeOS 技能與工作流程。",
  "Manage the public daemon profile — a digital representation of what you're working on. DaemonAggregator reads LifeOS sources (TELOS, KNOWLEDGE, PROJECTS, MEMORY/WORK, identity) → daemon-data.json. SecurityFilter strips names/paths/credentials via deterministic patterns (NOT LLM). Workflows: UpdateDaemon, ReadDaemon, PreviewDaemon, DeployDaemon. USE WHEN daemon, update daemon, daemon profile, deploy daemon, preview daemon, read daemon, public profile, digital presence. NOT FOR LifeOS system management.": "將意圖、知識、專案與工作狀態整理為公開近況資料。",
  "Detects AI-generated writing four ways — a heuristic audit against a catalog of known AI patterns, deterministic statistical signals (n-gram entropy, burstiness, repetition, stylometry — features never verdicts), an empirical Pangram score calibrated against known-human baselines, and a keyless scan for watermark and steganography signatures (invisible characters, homoglyphs, bidi, odd whitespace) in the bytes. USE WHEN detect AI writing, is this AI, AI detection, AI detector, did an AI write this, does this sound like AI, AI writing score, pangram, scan for AI tells, flag AI patterns, AI-isms, statistical AI signals, burstiness, text entropy, is this watermarked, detect watermark, steganography, zero-width chars, hidden characters, invisible unicode, compare drafts for AI-ness. NOT FOR rewriting prose to strip AI patterns (use a voice/authoring skill), plagiarism detection, detecting AI-generated images/video/code, or judging whether writing is any good.": "結合文字特徵、統計訊號與工具檢查人工智慧生成的可能跡象。",
  "Assertion-first AI eval framework aligned to Anthropic's 'Demystifying evals for AI agents' — typed deterministic asserts + a forced-structured LLM judge over an input→assert case schema, pass^k/pass@k, capability vs regression suites, subscription-billed. USE WHEN eval, evaluate, benchmark, regression test, assertion, assert, llm-rubric, judge, pass@k, pass^k, grade output, compare prompts/models, test agent. NOT FOR scientific-method framing (use Science), property/mutation testing of code (use Hardening), or live UI verification (use Interceptor).": "以明確斷言與評審規則評估代理輸出及穩定性。",
  "Content-adaptive wisdom extraction that reads content first, detects which wisdom domains are present, and builds custom sections around them, with five depth levels and mandatory contrarian takes; pulls YouTube via fabric and articles via WebFetch. USE WHEN extract wisdom, analyze video, analyze podcast, extract insights, key takeaways, summarize interview, distill content. NOT FOR static Fabric extract_wisdom pattern (use Fabric).": "依內容整理洞見、觀點與可行建議，並提出相反觀點。",
  "Execute any of 240+ specialized prompt patterns natively across Extraction, Summarization, Analysis, Creation, Improvement, Security, Rating. Common: extract_wisdom, create_threat_model, analyze_claims, improve_writing, review_code, mermaid, youtube_summary. CLI used only for YouTube transcript (-y) and URL fallback (-u). Two workflows: ExecutePattern, UpdatePatterns. USE WHEN fabric, fabric pattern, run fabric, update patterns, threat model, analyze claims, improve writing, review code, mermaid, STRIDE, sigma rules. NOT FOR multi-agent investigation (Research) or content-adaptive extraction (ExtractWisdom).": "使用現成的專門提示範本，處理擷取、摘要、分析與創作。",
  "Physics-based reasoning framework (Musk methodology) that deconstructs a problem to irreducible fundamental truths, classifies every element as hard constraint, soft constraint, or assumption, then reconstructs the optimal solution from fundamentals alone. USE WHEN first principles, fundamental truths, challenge assumptions, real constraint, rebuild from scratch, start over, physics first, question everything, reasoning by analogy. NOT FOR structural feedback loops (use SystemsThinking).": "拆解問題的基本事實、限制與假設，再重新推導方案。",
  "Renders the current session's output (analysis, research, red team, report, plan) as an extremely well-designed, self-contained HTML artifact via a deterministic renderer — the model distills content into typed JSON, the tool owns all layout/typography/color. USE WHEN /HTML, HTML artifact, render this as HTML, make this an HTML page, artifact of this analysis, designed HTML output. NOT FOR deployed websites or web apps (build the project directly), web UI design systems (use Webdesign), static images or diagrams (use Art), or writing the underlying analysis itself (run the analysis first, then /HTML renders it).": "將分析、研究與計畫整理成可獨立閱讀的 HTML 成果。",
  "Hardens LifeOS tests via property/mutation testing. USE WHEN harden, hardening, property test, property based testing, PBT, fast-check, mutation test, mutation testing, Stryker, CRAP score, CRAP analysis, DRY scan, jscpd, acceptance test mutation, strengthen tests, sharpen ISCs, find bugs example tests miss, universal quantified claim, shrink counterexample, what bugs am I missing, test the tests, test of the test. NOT FOR writing new feature tests (use bun test directly), grading agent output quality (use Evals), UI verification with real Chrome (use Interceptor), finding security vulnerabilities, or building new functionality.": "透過性質測試與變異測試，強化測試的可靠性。",
  "Owns the Ideal State Artifact — the primitive holding a project or task's articulated ideal state; scaffolds, interviews, grills a half-formed idea into shape via checkpointed discovery, scores completeness, reconciles feature excerpts to master, seeds from a repo, and appends decisions/changelog/verification across a locked seventeen-section order. USE WHEN ISA, ISC, ideal state, ideal state criteria, project specification, hill-climb, articulating done, fog, not yet specified, grill me, discovery interview. NOT FOR creating new skills (use CreateSkill).": "釐清理想成果與完成條件，建立並維護可驗證的目標文件。",
  "Evolutionary ideation engine — loop-controlled multi-cycle idea generation through phases of dreaming, cross-domain stealing, recombination, fitness testing, selection, and Lamarckian meta-learning, producing ranked novel solution candidates with provenance. USE WHEN ideate, id8, novel ideas, evolve ideas, dream up solutions, innovate, breakthrough ideas, idea evolution, multi-cycle creativity, need genuinely new approaches. NOT FOR quick single-pass brainstorming (use BeCreative).": "以多輪產生、組合、評估與選擇持續改進構想。",
  "Real Chrome/Brave + macOS Computer Use from inside the browser — zero CDP fingerprint, real sessions; mandatory for visual deploy verification. Drive clickwork yourself. USE WHEN verify deploy, confirm UI, screenshot verification, computer use, macos automation, debug web, troubleshoot, visual check, motion/animation bug, jank, transition stutter, scrub a flow, console logs/errors, runtime/JS/react errors, mismatch warning, network traffic/log, HAR/pcapng export, hydration/blank-page debug, flash then blank/page broken, why is this not working/what's happening on the page, authenticated page, bot detection bypass, reproduce bug, drive native app, about to ask the operator to click/navigate/fill a form/log in/approve OAuth, OAuth consent flow, complete a web login, do this in your browser. NOT FOR residential-proxy crawling (BrightData) or social actor scraping (Apify).": "操作真實瀏覽器並檢查介面、部署與可見成果。",
  "Evidence-grounded context refresh: reads constitutional files, TELOS, and CURRENT_STATE/IDEAL_STATE dimension files via TelosFreshness, pulls observed data (Oura sleep/HRV, Conduit app-time, work registry, git, expenses via StateEvidence), and drives a peer conversation that opens with claim-vs-evidence contradictions, drafts corrections for ratification, and closes with a ComputeGap-grounded ideal-state review. Routes to ContextCheckin; Phase0Setup on fresh install. USE WHEN /interview, resume interview, context check-in, telos check-in, what's stale, stale data, freshness check, update current state, update my current state, state sync, statusline says interview due, interview due, review TELOS, update ideal state, quarterly context refresh, fresh LifeOS install, configure DA name. NOT FOR single edits (Telos), bulk intake (Migrate), identity-only.": "根據個人方向與已有資料訪談，更新目前狀態及理想狀態。",
  "Structured multi-angle exploration running 2-8 sequential passes over the same problem, each through a different scientific lens, to surface hidden requirements and edge cases invisible from one angle; each pass yields new ISC criteria. USE WHEN iterative depth, explore deeper, multi-angle analysis, surface hidden requirements, blind spot check, what am I missing. NOT FOR scope/zoom analysis (use ApertureOscillation).": "以連續數輪不同視角探索問題，找出隱藏要求與邊界情況。",
  "Install and onboard a user into LifeOS — the Life Operating System (current state → ideal state via TELOS + the Algorithm). The agentic installer detects your OS + harness, wires hooks with permission, scaffolds your USER tree, pulls in sources you provide, and runs the TELOS / current→ideal interview that seeds your Pulse dashboard. USE WHEN install LifeOS, set up LifeOS, lifeos setup, lifeos-setup, lifeos interview, onboard me, run the interview, integrate LifeOS into my harness, update LifeOS, uninstall LifeOS, first-time setup, lifeos doctor, check my install, what capabilities are broken. NOT FOR building or cutting a LifeOS release (private release tooling), editing TELOS after onboarding (use Telos / Interview), or LifeOS system maintenance (use the private maintenance skill).": "安裝並設定 LifeOS，以個人方向與執行流程推進理想狀態。",
  "Generic civic intelligence aggregator for any US city — daily local digest of construction permits, crime, new businesses, public officials, legislation, elections, arrests, and local news, keyed off principal's Hometown. Writes JSON consumed by Pulse LOCAL tab. Crime delegates to a dedicated crime-stats skill. Workflows: DailyBrief, Construction, Crime, Business, Officials, Legislation, Elections, Arrests, News. USE WHEN local news, hometown news, council meeting, building permits, mayor, ballot measures, ordinance, recent arrests, civic intel, local digest. NOT FOR national news or arbitrary-city crime.": "彙整城市公共資訊、建設、商業與地方動態。",
  "Iterative improvement loop — refine a target across multiple Algorithm cycles toward ideal state. USE WHEN loop, iterate, refine, multiple passes, keep improving, revisit, rework.": "反覆檢視成果並修正，逐步接近理想狀態。",
  "Intakes external content, classifies chunks against LifeOS taxonomy, commits with provenance. Sources: .md/.txt, stdin, LifeOS dirs, CLAUDE.md/Cursor/OpenAI Custom Instructions, Obsidian/Notion/Apple Notes exports. MigrateScan classifies → routing table. MigrateApprove with --approve-all/--approve-target/--review/--dry-run. Confidence ≥70% auto, 40-70% confirm, <40% walk-through. USE WHEN /migrate, migrate content, import from other LifeOS, bring in old notes, import Cursor rules, import CLAUDE.md, bulk import, Obsidian/Notion/Apple Notes import. NOT FOR single-file edits, conversational interviews, identity edits.": "分類外部內容並匯入 LifeOS，保留來源與整理紀錄。",
  "Evolutionary explanation-discovery engine for hard-to-vary causal theories of unknown phenomena. USE WHEN develop a new theory, explain a mystery, solve an explanatory gap, discover a mechanism, consciousness, origin, or scientific breakthrough. Also use for multi-cycle creative exploration. NOT FOR a single-pass divergent brainstorm (use BeCreative) or delivery validation alone (use Evals).": "針對尚未解釋的現象，提出並改進可受檢驗的因果理論。",
  "Autonomous optimization loop — hill-climb any target. Code with metrics, or skills/prompts/agents with LLM-as-judge. USE WHEN optimize, hill climb, improve metric, reduce latency, optimize skill, optimize prompt, eval mode.": "依指標反覆調整程式、提示詞或技能，尋找更好的結果。",
  "Ethical people-finding and identity verification via parallel research agents across people-search sites, social media, public records, and reverse phone/email/image/username lookups, with confidence-scored results requiring 3+ matching identifiers. USE WHEN find person, locate person, reconnect, lost contact, old friend, reverse phone lookup, who owns this email, reverse image search, find by username, verify identity, people search, public-data background check, who is this caller. NOT FOR structured due-diligence or company/entity intelligence investigations, or general web research synthesis (use Research).": "透過公開且適當的來源查找人物與組織資訊，標示可信程度。",
  "Meta-prompting standard library for generating, optimizing, and composing prompts programmatically via Standards, Handlebars Templates, and Tools; output is always a prompt to use elsewhere, not final content. USE WHEN meta-prompting, template generation, prompt optimization, prompt engineering, write a prompt, create system prompt, Handlebars template, eval prompt, judge prompt. NOT FOR generating final content (use the appropriate domain skill).": "建立可重複使用、可組合與可改進的提示詞。",
  "Adversarial analysis deploying parallel expert agents to stress-test ideas, strategies, and plans — decomposes into atomic claims, attacks them, then steelmans and counter-argues, producing severity-ranked findings with remediation. USE WHEN red team, attack idea, counterarguments, critique, stress test, devil's advocate, find weaknesses, break this, poke holes, strongest objection. NOT FOR collaborative debate to find best path (use Council).": "從對抗角度檢查主張、策略與計畫，找出風險及弱點。",
  "Creates programmatic video with React via Remotion — compositions, sequences, and motion graphics animated with useCurrentFrame() and rendered to MP4. USE WHEN video, animation, motion graphics, video rendering, React video, render video, animate content, make a short, create animations, video overlay, explainer video, animated explainer, content to video, programmatic video. NOT FOR static images, diagrams, or illustrations (use Art), tight-cut filler removal from raw talking-head recordings (that is video editing, not motion graphics), or audio-only podcast cleaning (use AudioEditor).": "使用 React 與 Remotion 製作動畫、字幕與影片。",
  "Multi-agent web research with mandatory URL verification, confidence-tagged output, and four depth modes (quick to deep investigation). USE WHEN research, do research, quick research, extensive research, deep investigation, find information, investigate, extract alpha, analyze content, retrieve content, AI trends, enhance content, extract knowledge, web scraping, YouTube extraction, map landscape, competitive analysis, find it, find this, find this product, identify this, what is this, what's that thing, track down, locate, help me find, I can't find X online, can't find it online, source this — never substitute raw WebSearch/WebFetch for a multi-source find/identify/investigate request. NOT FOR people/company/entity deep background, academic papers (use ArXiv), JSON entity extraction, or content-adaptive wisdom extraction (use ExtractWisdom).": "以多來源搜尋與交叉核對完成研究，驗證引用網址。",
  "Structured incident investigation using Five Whys, Fishbone, blameless Postmortem, Fault Tree, Kepner-Tregoe, and FMEA — traces failures to systemic root causes rather than blaming humans. USE WHEN root cause, RCA, 5 whys, fishbone, postmortem, incident analysis, fault tree, why does this keep failing, blameless, recurring bug. NOT FOR systemic loops (use SystemsThinking).": "以結構化方法追查問題的系統性原因與改善方向。",
  "Transforms product documentation into sales-ready packages — a story explanation, charcoal gestural sketch art, and talking points — via a narrative-arc pipeline. USE WHEN sales, proposal, pitch deck, value proposition, sales narrative, sales deck, sales package, turn this into a pitch, create a sales story, sales materials, product pitch, transform docs to sales, sales script. NOT FOR Hormozi $100M frameworks, value equation, irresistible offer, or VOC mining, standalone diagrams or illustrations (use Art), or platform social posts.": "將產品資訊整理成故事、視覺與提案重點。",
  "The scientific method as a universal problem-solving algorithm — goal-first, plural falsifiable hypotheses, designed experiments, and honest measurement, scaling from TDD to feature validation to MVP launch. USE WHEN think about, figure out, experiment, iterate, optimize, hypothesis, science, full cycle, quick diagnosis, structured investigation, how do we test, analyze results. NOT FOR multi-angle lens passes (use IterativeDepth).": "以目標、假說、實驗與測量檢驗問題及解法。",
  "Query curated cybersecurity market and company intelligence. USE WHEN security market data OR cybersecurity funding OR cyber M&A OR security-company/investor research OR market maps OR deal activity OR Return on Security OR The Signal. NOT FOR vulnerability research, security news, or investment advice.": "查詢資安公司、市場、投資及併購資訊。",
  "Discover WHICH new skills you should create, from your own work history plus your satisfaction/frustration signals. Read-only and proposal-only: it surfaces recurring pain that no existing skill, loop, or workflow covers, then hands you a ranked shortlist to build with CreateSkill. It never creates or edits a skill itself. Frustration is a first-class signal (a topic can look 'covered' while you keep hitting the same wall inside it), so it reads low ratings and recurrence markers, not just session topics. USE WHEN should I create a skill, what skills do I need, suggest skills, skill gap, based on my recent work, am I missing a skill, what should I build. NOT FOR creating/validating/testing/optimizing an individual skill (use CreateSkill) — this only decides WHAT to build, not how.": "根據工作紀錄與使用回饋，找出值得建立的新技能。",
  "Structural analysis of complex systems — Iceberg model, Causal Loop feedback diagrams, archetype matching, Meadows leverage points, and concept maps — grounded in the premise that behavior is generated by structure. USE WHEN systems thinking, causal loop, feedback loops, archetypes, leverage points, iceberg model, fix the system, why does this keep happening, recurring problem, second-order effects. NOT FOR incident causal chains (use RootCauseAnalysis).": "使用因果關係、回饋循環與系統結構分析問題。",
  "Interactive voice-narrated tutorial on whatever the current conversation is about — teaches the topic beat by beat with ASCII diagrams in the terminal while speaking the actual lesson content aloud, asking one question per beat and quizzing until the ideas land. USE WHEN teach me, /teach-me, tutorial, teach me this, walk me through this interactively, explain this like a lesson, learn mode, quiz me, help me actually understand what we just did. NOT FOR plain written explanations with no dialogue (just answer directly), authored/published content, or discovery interviews that shape a half-formed idea (use grill-me).": "以分段說明、圖解與語音協助理解主題。",
  "Dual-context skill: Personal TELOS reads and updates goals, beliefs, narratives, strategies, and more with timestamped backups; Project TELOS analyzes .md/.csv directories for dependency chains, bottlenecks, and alignment, generating reports, narrative points, or dashboards. USE WHEN Telos, life goals, projects, dependencies, update TELOS, narrative points, McKinsey report, dashboard, what am I wrong about, life frames, mental models. NOT FOR conversational constitutional review (use Interview).": "整理使命、目標、信念、策略及專案之間的關係。",
  "Defensive threat modeling and risk management for your own estate — map where sensitive data lives across your asset graph, run compromise scenarios (what a hacked asset exposes, its blast radius, how you'd respond), and maintain a persistent risk register with likelihood×impact scoring, owners, mitigations, and review cadence via a deterministic CLI. All real data stays in your private USER tree; this skill is code only. USE WHEN threat model, threat modeling, risk register, risk assessment, what if X got hacked, compromise scenario, blast radius, sensitive data map, where is our sensitive data, data classification, risk review, add a risk, accept a risk, security risk posture. NOT FOR active pentesting or exploitation (use an offensive-security skill), world-scale futures stress-testing of ideas (use WorldThreatModel), or executing incident response (use your incident-response runbooks — this skill plans them).": "辨識重要資料與資產、推演攻擊情境並評估防禦風險。",
  "Read, create, and edit tldraw .tldr canvas files deterministically — sketch hand-drawn-register diagrams (boxes, arrows, sticky notes, frames, text) directly into a canvas file the user opens in any tldraw surface, and read a rough canvas back as structured data to organize it. USE WHEN tldraw, .tldr file, whiteboard, canvas, sketch a diagram, hand-drawn diagram, draw this on a canvas, put this on the whiteboard, structure my canvas, organize my whiteboard, read my canvas, cluster my sticky notes. NOT FOR polished static images, infographics, or mermaid diagrams (use Art), web UI design (use Webdesign), programmatic video (use Remotion).": "建立與編輯可在 tldraw 開啟的圖解畫布。",
  "Reduces an always-on LifeOS context file that has grown too big via a human-gated pass — deterministic GC of stale entries first, then semantic merges and relocations — never dropping a directive and committing every change reversibly. USE WHEN /trim, trim the context, trim OPERATIONAL_RULES, this file is too big, reduce a doctrine file, prune an always-loaded file, fold the proposal inbox, shrink CLAUDE.md or DA_IDENTITY. NOT FOR general code refactoring, trimming video or audio media (use AudioEditor for audio files), or removing AI writing patterns from prose.": "整理常駐背景，刪除過時內容並整合重複資訊。",
  "Analyze and update 68 US economic and social indicators from five government APIs (FRED, EIA, Treasury, BLS, Census) across 10 categories: GDP, Inflation, Employment, Housing, Consumer Finance, Markets, Trade, Government/Fiscal, Demographics, Health. Two workflows: UpdateData, GetCurrentState (10y/5y/2y/1y trend analysis). USE WHEN GDP, inflation, unemployment, economic metrics, gas prices, how is the economy, refresh data, FRED, US metrics, economic trends. NOT FOR pathogen surveillance.": "彙整美國政府來源的經濟與社會指標。",
  "Improve LifeOS from what the best practitioners are shipping around AI harnesses — Anthropic first (changelogs, docs, releases), then trusted creators, trending repos, and the system's own reflections — extracting concrete techniques and filtering them against verified current state so nothing already-done or rejected is re-recommended. USE WHEN upgrade, system upgrade, check Anthropic, new Claude features, algorithm upgrade, LifeOS upgrade, mine reflections.": "研究外部實踐與自身經驗，提出 LifeOS 改進。",
  "macOS system performance diagnostics — see how the machine is running and what's slowing it down: CPU/GPU/memory/energy hogs, thermal throttling, memory and swap pressure, disk usage, Spotlight indexing, launchd/startup load, via a deterministic read-only CLI with known-process interpretation (kernel_task, WindowServer, mds_stores). USE WHEN mac slow, system slow, what's slowing down my mac, computer is slow, what's eating CPU, CPU usage, GPU usage, what's using the GPU, memory pressure, RAM usage, swap, runaway process, fans loud, mac running hot, thermal throttling, system health, check my mac, how's my system running, top processes, energy hogs, activity monitor, startup items, launch agents load, system taxed. NOT FOR network/wifi diagnostics, website or deployed-app health monitoring, or security scanning.": "檢查 macOS 的處理器、記憶體、耗能、溫度與背景活動。",
  "Design and integrate web interfaces via three paths: DirectDesign (write design inline with Anthropic frontend-design philosophy — the default workhorse), native /design + /design-sync Claude Code commands (preferred for code integration and design-system sync), or ClaudeDesign (drive claude.ai/design through Interceptor — experimental visual-review fallback). USE WHEN web design, UI design, create prototype, design system, design sync, redesign site, mockup, landing page, dashboard design, design-to-code, frontend design, polish UI, design audit, brutalist/editorial/retro UI. NOT FOR illustrations/logos (use Art) or video (use Remotion).": "設計並實作網頁介面與互動。",
  "Persistent world-model harness that stress-tests ideas, strategies, and investments against 11 time horizons from 6 months to 50 years, each a deep analysis of geopolitics, tech, economics, society, and security, in Fast/Standard/Deep tiers. USE WHEN threat model, world model, test idea, future analysis, time horizon, stress test against future, long-term risk. NOT FOR single-shot idea attack (use RedTeam).": "跨多個時間尺度檢查地緣、技術、經濟與社會情境。",
  "Scaffolding that helps a writer build a story they already want to tell — fills in structure, hidden wound, theme, and prose from the writer's own material across seven narrative layers, deriving the spine from their notes as proposals they ratify. Bans generic AI patterns; scales short story to multi-book series. USE WHEN write story, fiction, novel, chapter, story bible, character arc, plot outline, creative writing, worldbuilding, draft story, help me write my story, develop my novel, layer my story, build out my book, I have notes for a story. NOT FOR narrative summaries of real content.": "整理角色、衝突、主題與敘事層次，協助發展故事。"
};

// Locally installed character and notes skills; display metadata only.
Object.assign(SKILL_NAMES, {
  "ai-character-director": "視覺人物設計",
  "ai-character-roleplay": "角色與人格設計",
  "得到大脑（Get笔记）": "得到筆記",
  "getnote": "得到筆記"
});
Object.assign(SKILL_DESCRIPTIONS, {
  "创建、迭代并管理可复用的视觉 AI 人物。适用于品牌人物、叙事角色、数字代言人、豪宅空间向导等场景；用于保持跨图片、镜头、服装和视频分镜的人物一致性，调整年龄、脸、发型、造型与情绪，并形成角色圣经、提示词包、定妆照组和连续性检查体系。": "建立並維護視覺人物，統一外貌、造型、情緒與分鏡，保持跨圖片及影片的一致性。",
  "Create, refine, and operate role-playing AI characters and persona-driven agents. Use when Codex needs to turn a user idea, story setting, NPC, companion, tutor, mascot, branded spokesperson, or digital-clone concept into a believable character with a persona card, system prompt, dialogue samples, memory plan, safety boundaries, or evaluation checklist.": "設計可互動的角色與代理，整理人格、對話範例、記憶方式及行為界線。",
  "得到大脑（Get笔记）- 保存、搜索、管理个人笔记和知识库。\n\n**当以下情况时使用此 Skill**：\n(1) 用户要保存内容到笔记：发链接、发图片、说「记一下」「存到笔记」「保存」「收藏」\n(2) 用户要搜索或查看笔记：「搜一下」「找找笔记」「最近存了什么」「看看原文」\n(3) 用户要管理知识库或标签：「加到知识库」「建知识库」「加标签」「删标签」\n(4) 用户要配置 得到大脑（Get笔记）：「配置笔记」「连接得到大脑（Get笔记）」\n": "儲存、搜尋與整理個人筆記、標籤及知識庫。"
});

// Display-only names for the bundled documentation; document bodies and routes stay unchanged.
const DOC_LABELS: Record<string, string> = {
  "Documentation": "文件",
  "Overview": "總覽",
  "Agents": "代理協作",
  "Algorithm": "思考流程",
  "Arbol": "雲端工作流程",
  "Atlas": "資源地圖",
  "Bunker": "應用管理",
  "Conduit": "活動感知",
  "Config": "設定",
  "Delegation": "任務委派",
  "Fabric": "提示範本",
  "Feed": "資訊流",
  "Freshness": "資料更新",
  "Hermes": "助理服務",
  "Hooks": "事件處理",
  "ISA": "理想狀態文件",
  "Ledger": "變更紀錄",
  "LifeOs": "生活作業系統",
  "Memory": "記憶",
  "Notifications": "通知",
  "Observability": "活動觀測",
  "Pulse": "工作台",
  "Router": "路由",
  "Security": "安全",
  "Services": "背景服務",
  "Skills": "技能",
  "Spinner": "進度提示",
  "Synapse": "想法收集",
  "Terminal": "終端機",
  "Testing": "測試",
  "Tools": "工具",
  "Upgrades": "系統改進",
  "Work": "工作",
  "Writing": "寫作",
  "LifeOS Architecture Summary": "LifeOS 架構摘要",
  "LifeOS Brand Assets": "LifeOS 品牌素材",
  "LifeOS Constitutional Rules": "LifeOS 核心規則",
  "LifeOS Core Components": "LifeOS 核心元件",
  "System / User Boundary": "系統與使用者資料界線",
  "What LifeOS is and Why it Exists": "LifeOS 是什麼與存在理由",
  "LifeOS Agent System": "LifeOS 代理系統",
  "Algorithm Changelog": "思考流程變更紀錄",
  "Ascent States — what a run is doing, everywhere": "工作狀態：目前正在做什麼",
  "eval-guide": "評測指南",
  "Ideate Loop Protocol — Moved": "構想演化流程（已移動）",
  "Optimize Loop Protocol — Moved": "優化流程（已移動）",
  "The Algorithm — the LifeOS Thinking System": "LifeOS 思考流程",
  "The Algorithm 8.20.2": "思考流程 8.20.2",
  "Arbol — the LifeOS Cloud Execution Layer": "Arbol 雲端執行層",
  "Atlas — the LifeOS Asset Graph": "Atlas 資源關係圖",
  "Bunker — the Universal Application Harness": "Bunker 應用管理框架",
  "Conduit — LifeOS's Sensory Layer": "Conduit 活動感知層",
  "LifeOS Configuration": "LifeOS 設定",
  "Delegation & Parallelization Reference": "任務委派與平行處理參考",
  "Fabric Pattern System Reference": "Fabric 提示範本系統參考",
  "Feed — the LifeOS External Sense": "Feed 外部資訊流",
  "Freshness System": "資料更新狀態系統",
  "Hermes Sidecar — talk to your LifeOS as an agent": "Hermes 助理服務",
  "Hook System": "事件處理系統",
  "ISA Hierarchy & Cross-ISA Integration": "理想狀態文件階層與整合",
  "ISA HTML Mirror": "理想狀態文件 HTML 預覽",
  "LifeOS ISA Format Specification v2.21.0 (Algorithm v8.20.0)": "理想狀態文件格式 v2.21.0（思考流程 v8.20.0）",
  "The ISA — Ideal State Articulation": "理想狀態的表述",
  "Ledger — the LifeOS Change-Tracking System": "Ledger 變更追蹤系統",
  "Life OS Schema": "生活作業系統資料結構",
  "LifeOS — The Life Operating System Thesis": "LifeOS 生活作業系統理念",
  "RenamePlan — PAI → LifeOS": "更名計畫：PAI → LifeOS",
  "Cortex — the LifeOS Memory System": "Cortex 記憶系統",
  "Cortex Local Contract, Privacy Boundary, and Evidence Gates": "Cortex 本機約定、隱私界線與證據檢查",
  "Curation Coverage — what LifeOS autonomic systems touch": "內容整理範圍：自動系統接觸的資料",
  "The Notification System": "通知系統",
  "The Observability System": "活動觀測系統",
  "Custom Tooltips": "自訂提示",
  "LifeOS Digital Assistant Subsystem": "LifeOS 數位助理子系統",
  "Pulse — the Life Dashboard": "Pulse 生活工作台",
  "Pulse Metadata Surface — Badges, Strips, Panels": "Pulse 資訊呈現：標籤、狀態列與面板",
  "Terminal Tab State System": "終端機分頁狀態系統",
  "The Router": "路由系統",
  "LifeOS Data Classification & Inference-Source Routing": "LifeOS 資料分類與推理來源路由",
  "LifeOS Security — Minimal v2": "LifeOS 安全設計：精簡版 v2",
  "LifeOS Security Model": "LifeOS 安全模型",
  "LifeOS Background Services": "LifeOS 背景服務",
  "Custom Skill System": "自訂技能系統",
  "Custom Spinner Verbs": "自訂進度提示文字",
  "Synapse — the LifeOS Input Router": "Synapse 想法收集與分流",
  "Helm — the LifeOS Terminal (Optional)": "Helm 終端機（選用）",
  "LifeOS Testing Doctrine": "LifeOS 測試準則",
  "CLI-First Architecture Pattern": "命令列優先的架構",
  "LifeOS Command-Line Tools": "LifeOS 命令列工具",
  "LifeOS Containment Policy": "LifeOS 內容範圍原則",
  "LifeOS Tools - CLI Utilities Reference": "LifeOS 命令列工具參考",
  "The Upgrades System": "系統改進流程",
  "Work System": "工作系統",
  "AI Writing Patterns — Detection Reference": "人工智慧寫作特徵檢查參考",
};

export function docDisplayLabel(value: string): string {
  return DOC_LABELS[value] ?? value;
}

export function moduleLabel(value: string): string {
  return MODULE_LABELS[value] ?? value;
}

export function skillDisplayName(name: string): string {
  return SKILL_NAMES[name] ?? name;
}

export function skillDisplayDescription(description: string, name?: string): string {
  // The legacy API exposes a YAML block marker instead of this known skill's description.
  if (description === "|" && (name === "得到大脑（Get笔记）" || name === "getnote")) return "儲存、搜尋與整理個人筆記、標籤及知識庫。";
  return SKILL_DESCRIPTIONS[description] ?? description;
}
